### ISSUE TITLE
Project Submission Not Allowed - New Milestone Project

### ISSUE THREAD

**Issue by FreeLydia** [microverseinc/microverse-issue-tracker#17] opened 2019-09-11 10:20 UTC
Received this message from student Kerron Shawn King, GH account: https://github.com/KerronKing

Hi.

My pull request for the third Milestone of the collaborative OOP Ruby project was approved. However, the dashboard still displays "changes required". My partner was able to submit his completion form but my dashboard does not yet display "submit form". Any help in this matter would be greatly appreciated.

@Keqi @nidalaa - Please look into this one.

**Comment by nidalaa** [comment] 2019-09-13 14:49
Duplicate of https://github.com/microverseinc/microverse-issue-tracker/issues/12

**Closed by nidalaa** 2019-09-13 14:49 UTC
Labels: bug
