### ISSUE TITLE
Project status not changed on "Testing Your Ruby Code - Enumerable" project

### ISSUE THREAD

**Issue by zhuchini** [microverseinc/microverse-issue-tracker#101] opened 2019-10-22 21:49 UTC
It's a collaborative project and my partner sent a code review and was approved. The status of the project still shows "Request Code Review" on my side.

**Comment by Keqi** [comment] 2019-10-24 13:33
Hi @zhuchini,

Thanks for the request. Who is your coding partner? I can't find any active partner relationships for you.

**Comment by zhuchini** [comment] 2019-10-24 14:59
It was Aaron Rory Newbold. He just finished the SQL project and got a new partner.

**Comment by Keqi** [comment] 2019-10-29 05:46
Hi @zhuchini,

From what I can see, you have submitted a `Project Completion` form for this project and marked it as completed. The scenario which you mentioned in the first post could be caused by your partner checking `I worked solo on this project` checkbox while submitting a Code Review Request.

If you both completed the project and submitted the form, it's all good.

**Closed** 2019-10-31 14:16 UTC
